version: '3.4'

services:
  db:
    container_name: db
    image: rest-with-asp-net-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net
    ports:
      - 3309:3306
    networks:
      - udemy-network

  rest-with-asp-net:
    container_name: rest-with-asp-net
    image: rest-with-asp-net
    build:
      context: .
      dockerfile: RestWithASPNET/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge